type Token {
    access_token: String!
}

type UserPayload {
    id: ID!
    username: String!
    email: String!
    role: Role! 
}

input LoginUser {
    username: String!
    password: String!
}

type QueryAuth {
    userCurrent: UserPayload! @goField(forceResolver: true)
}

type MutationAuth {
    loginUser(input: LoginUser!): Token! @goField(forceResolver: true)
}