directive @goField(
  forceResolver: Boolean
  name: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

# new directive
directive @auth on FIELD_DEFINITION

scalar Time

enum Status {
    ACTIVE
    INACTIVE
    PREACTIVE
}

type Query {
    user: QueryUser! @goField(forceResolver: true)
    profile: QueryProfile! @goField(forceResolver: true)
    auth: QueryAuth! @goField(forceResolver: true)
}


type Mutation {
   user: MutationUser! @goField(forceResolver: true)
   auth: MutationAuth! @goField(forceResolver: true)
}


