directive @goField(
  forceResolver: Boolean
  name: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION | OBJECT | INTERFACE | UNION | ENUM | ENUM_VALUE | SCALAR | INPUT_OBJECT | ARGUMENT_DEFINITION | INTERFACE | UNION | ENUM | ENUM_VALUE | SCALAR | INPUT_OBJECT | ARGUMENT_DEFINITION

scalar Time

enum Status {
    ACTIVE
    INACTIVE
    PREACTIVE
}

type Query {
    QueryUser: QueryUser! @goField(forceResolver: true)
    QueryProfile: QueryProfile! @goField(forceResolver: true)
    QueryAuth: QueryAuth! @goField(forceResolver: true)
}


type Mutation {
   MutationUser: MutationUser! @goField(forceResolver: true)
   MutationAuth: MutationAuth! @goField(forceResolver: true)
}


