// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type MutationUser struct {
	CreateUser *User `json:"createUser"`
	UpdateUser *User `json:"updateUser"`
	DeleteUser *User `json:"deleteUser"`
}

type Query struct {
}

type QueryProfile struct {
	GetProfileUserByID *Profile `json:"getProfileUserById"`
}

type QueryUser struct {
	Users       []*User `json:"users,omitempty"`
	GetUserByID *User   `json:"getUserById"`
}
