package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"apiturnos/src/constants"
	"apiturnos/src/generated"
	"apiturnos/src/schema/model"
	"context"
)

// LoginUser is the resolver for the loginUser field.
func (r *mutationAuthResolver) LoginUser(ctx context.Context, obj *model.MutationAuth, input model.LoginUser) (*model.Token, error) {
	return r.authService.Login(ctx, input)
}

// UserCurrent is the resolver for the userCurrent field.
func (r *queryAuthResolver) UserCurrent(ctx context.Context, obj *model.QueryAuth) (*model.UserPayload, error) {
	payload, _ := ctx.Value(constants.TokenDataKey).(*model.UserPayload)
	return payload, nil
}

// MutationAuth returns generated.MutationAuthResolver implementation.
func (r *Resolver) MutationAuth() generated.MutationAuthResolver { return &mutationAuthResolver{r} }

// QueryAuth returns generated.QueryAuthResolver implementation.
func (r *Resolver) QueryAuth() generated.QueryAuthResolver { return &queryAuthResolver{r} }

type mutationAuthResolver struct{ *Resolver }
type queryAuthResolver struct{ *Resolver }
