package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/diegofly91/apiturnos/src/generated"
	"github.com/diegofly91/apiturnos/src/schema/model"
)

// GetProfileUserByID is the resolver for the getProfileUserById field.
func (r *queryProfileResolver) GetProfileUserByID(ctx context.Context, obj *model.QueryProfile, userID int) (*model.Profile, error) {
	panic(fmt.Errorf("not implemented: GetProfileUserByID - getProfileUserById"))
}

// QueryProfile returns generated.QueryProfileResolver implementation.
func (r *Resolver) QueryProfile() generated.QueryProfileResolver { return &queryProfileResolver{r} }

type queryProfileResolver struct{ *Resolver }
