// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type MutationAuth struct {
	//  Mutation type allows fetching auth login.
	LoginUser *Token `json:"loginUser"`
}

type MutationProfile struct {
	CreateProfileUser *Profile `json:"createProfileUser"`
	UpdateProfileUser *Profile `json:"updateProfileUser"`
}

type MutationUser struct {
	CreateUser     *User `json:"createUser"`
	UpdatePassword *User `json:"updatePassword"`
	DeleteUser     *User `json:"deleteUser"`
}

type Query struct {
}

// QueryAuth is the query type for authentication
type QueryAuth struct {
	//  Query info context user act. @auth
	UserCurrent *UserPayload `json:"userCurrent"`
}

type QueryProfile struct {
	GetProfileUserByID *Profile `json:"getProfileUserById"`
}

// QueryUser is the query type for user
type QueryUser struct {
	//  Query info all users. @@hasRole(roles: [ADMIN, GUEST])
	Users       []*User `json:"users,omitempty"`
	GetUserByID *User   `json:"getUserById"`
}
