package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/diegofly91/apiturnos/src/generated"
	"github.com/diegofly91/apiturnos/src/model"
)

// User is the resolver for the user field.
func (r *mutationResolver) User(ctx context.Context) (*model.MutationUser, error) {
	return &model.MutationUser{}, nil
}

// Auth is the resolver for the auth field.
func (r *mutationResolver) Auth(ctx context.Context) (*model.MutationAuth, error) {
	return &model.MutationAuth{}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.QueryUser, error) {
	return &model.QueryUser{}, nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*model.QueryProfile, error) {
	return &model.QueryProfile{}, nil
}

// Auth is the resolver for the auth field.
func (r *queryResolver) Auth(ctx context.Context) (*model.QueryAuth, error) {
	return &model.QueryAuth{}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
