package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/diegofly91/apiturnos/src/generated"
	"github.com/diegofly91/apiturnos/src/model"
)

// MutationUser is the resolver for the MutationUser field.
func (r *mutationResolver) MutationUser(ctx context.Context) (*model.MutationUser, error) {
	return &model.MutationUser{}, nil
}

// QueryUser is the resolver for the QueryUser field.
func (r *queryResolver) QueryUser(ctx context.Context) (*model.QueryUser, error) {
	return &model.QueryUser{}, nil
}

// QueryProfile is the resolver for the QueryProfile field.
func (r *queryResolver) QueryProfile(ctx context.Context) (*model.QueryProfile, error) {
	return &model.QueryProfile{}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
