type Profile {
    id: ID!
    userId: ID!
    email: String!
    firstname: String
    lastname: String
    createdAt: Time!
    updatedAt: Time!
}

type QueryProfile {
   getProfileUserById(userId: Int!): Profile! @goField(forceResolver: true)
}