type Profile {
    id: ID!
    userId: ID! @goField(name: "user_id")
    firstname: String
    lastname: String
    createdAt: Time!
    updatedAt: Time!
}

type QueryProfile {
   getProfileUserById(userId: Int!): Profile! @goField(forceResolver: true)
}