type Profile {
    id: ID!
    userId: ID!
    email: String!
    firstname: String
    lastname: String
    createdAt: Time!
    updatedAt: Time!
}

input ProfileInput {
    email: String!
    firstname: String
    lastname: String
}

type QueryProfile {
   getProfileUserById(userId: ID!): Profile! @goField(forceResolver: true)
}

type MutationProfile {
    createProfileUser(userId: ID!, input: ProfileInput!): Profile! @goField(forceResolver: true)
    updateProfileUser(userId: ID!, input: ProfileInput!): Profile! @goField(forceResolver: true)
}